InMAPData= "/data/home/wuruili/WORK/11.InMAP/inmap161_China/inmap_wrfcmaq_2017_Jan-Dec-d01-test.ncf"
[VarGrid]
GridProj= "+proj=lcc +lat_1=25.000000 +lat_2=40.000000 +lat_0=34.000000 +lon_0=110.000000 +x_0=0 +y_0=0 +a=6370000.000000 +b=6370000.000000 +to_meter=1"

[Preproc]
CTMType= "WRF-Cmaq"
StartDate= "20170101"
EndDate= "20171231"
CtmGridXo= -3096000.0
CtmGridYo= -2286000.0
CtmGridDx= 36000.0
CtmGridDy= 36000.0

[Preproc.WRFCmaq]
WRFOut= "/data/home/wuruili/0.Model/11.InMAP/wrfcamq2inmap/wrfcmaq2inmap/daily/wrfcmaq_[DATE].ncf"
